name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.5
    - name: Build and test with Rake
      run: |
        gem install bundler:1.17.3
        gem install sqlite3 -v '1.4.0' --source 'https://rubygems.org/'
        bundle install --jobs 4 --retry 3
        bundle exec rake
